app:
  swagger:
    title: swift-mx-adapter
    description: Shared API Template
    version: 0.0.1-SNAPSHOT
    basePackage: com.rbc.bbp0
  active-mq-lms:
    broker-url: ${vcap.services.swift-mx-adapter-ups-credentials.active-mq-lms-broker-url:tcp://localhost:61616}
    user: ${vcap.services.swift-mx-adapter-ups-credentials.active-mq-lms-username:admin}
    password: ${vcap.services.swift-mx-adapter-ups-credentials.active-mq-lms-password:admin}
    queues:
      camt060:
        name: lms.incoming.camt.060.out
        baseFolder: static/

spring:
  application:
    name: swift-mx-adapter
  profiles:
    active: ${vcap.services.swift-mx-adapter-ups-credentials.env-active-profiles}
logging:
  level:
    com.rbc.bbp0: debug
    com.rbc.ue90: debug
    com.netflix:  debug
client:
  user:
    name: ${vcap.services.swift-mx-adapter-ups-credentials.security-username:bbp0}
    password: ${vcap.services.swift-mx-adapter-ups-credentials.security-password:Password123}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8082

spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
